import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "swiper/css";
import "./globals.css";
import { Header } from "@/widgets/header/index";
import { Footer } from "@/widgets/footer";

const ptSans = PT_Sans({
  weight: ["400", "700"],
  variable: "--font-pt-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${ptSans.variable} min-h-screen antialiased`}>
        <div className="flex min-h-screen w-full flex-col items-center bg-[white]">
          <div className="content-container flex w-[1100px] flex-1 flex-col">
            <Header />
            <main className="flex-1">{children}</main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
