import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "swiper/css";
import "./globals.css";
import { Header } from "@/widgets/header/index";

const ptSans = PT_Sans({
  weight: ["400", "700"],
  variable: "--font-pt-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="w-full bg-white flex items-center flex-col">
          <div className="content-container w-[1100px]">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
